### ISSUE TITLE
import-to-aur4.sh claims to import an empty repository

### ISSUE THREAD

**Issue by hobarrera** [ido/packages-archlinux#41]
When running `./import-to-aur4.sh https://github.com/hobarrera/aur-packages ""` a great deal of packages [are imported](https://aur-dev.archlinux.org/packages/?SeB=m&K=hobarrera) successfully, however, after all those, an error arises:

```
+ for p in '${PACKAGES[@]}'
+ git submodule add ssh+git://aur@aur-dev.archlinux.org:2222/opensmtpd-git.git/ opensmtpd-git
Cloning into 'opensmtpd-git'...
remote: Counting objects: 23, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 23 (delta 10), reused 0 (delta 0)
Receiving objects: 100% (23/23), done.
Resolving deltas: 100% (10/10), done.
Checking connectivity... done.
+ for p in '${PACKAGES[@]}'
+ git submodule add ssh+git://aur@aur-dev.archlinux.org:2222/opensmtpd-snapshot.git/ opensmtpd-snapshot
Cloning into 'opensmtpd-snapshot'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
fatal: You are on a branch yet to be born
Unable to checkout submodule 'opensmtpd-snapshot'
```

**Comment by ido** [comment]
Hi @hobarrera,
  I am only accepting pull requests for import-to-aur4.sh.  I do not have time to resolve issues related to it not working for your specific repository.  I wrote import-to-aur4.sh quickly to import the packages in this repository, and showed it off on the AUR mailing list as a demonstration.  If you would like to contribute back any improvements you make to it, I would welcome that and appreciate it, but I have to close this issue.

Please submit a PR if you fix the problem.  Have a good weekend!
