### ISSUE TITLE
ceph: rbd rwlock crash

### ISSUE THREAD

**Issue by thorwald** [ido/packages-archlinux#47]
In the latest version rwunlock-sigill-fix.patch was removed for some reason, resulting in this crash:

$ rbd ls
<list of volumes>
*** Caught signal (Segmentation fault) **
 in thread 7f63377f6780
 ceph version 0.87.1 (283c2e7cfa2457799f534744d7d549f83ea1335e)
 1: rbd() [0x427625]
 2: (()+0x10740) [0x7f633444e740]
 3: (pthread_rwlock_unlock()+0x12) [0x7f633444a4a2]
 4: (Objecter::OSDSession::~OSDSession()+0xfc) [0x7f6336f2681c]
 5: (Objecter::OSDSession::~OSDSession()+0x9) [0x7f6336f26969]
 6: (RefCountedObject::put()+0x44) [0x7f6336f45784]
 7: (Objecter::put_session(Objecter::OSDSession*)+0x1a9) [0x7f6336f20f09]
 8: (Objecter::close_session(Objecter::OSDSession*)+0x52d) [0x7f6336f30ebd]
 9: (Objecter::shutdown()+0x8b) [0x7f6336f312fb]
 10: (librados::RadosClient::shutdown()+0x1ea) [0x7f6334a160da]
 11: (librados::Rados::shutdown()+0x28) [0x7f63349fa378]
 12: (main()+0x4fd) [0x40e21d]
 13: (__libc_start_main()+0xf0) [0x7f6333b96800]
 14: (_start()+0x29) [0x415859]
2015-04-13 15:00:45.000981 7f63377f6780 -1 *** Caught signal (Segmentation fault) **
 in thread 7f63377f6780

And as you can see in the ceph repo, this patch was not applied to 0.87.1 upstream: https://github.com/ceph/ceph/blob/283c2e7cfa2457799f534744d7d549f83ea1335e/src/common/RWLock.h#L48

I confirmed this patch is still needed by manually re-adding the patch and the problem went away.

**Comment by ido** [comment]
Ceph is now in [extra].
