### ISSUE TITLE
import-to-aur4: what is the script doing?

### ISSUE THREAD

**Issue by JonnyJD** [ido/packages-archlinux#55]
I know you basically wrote the script for your own use and don't intend to "maintain" it or anything like that.
But maybe you can tell in a couple sentences what the script is actually doing?
It sounds it is exactly what I need, but I don't understand at all what it is doing:

What I got from  [the wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#AUR_4):
packages in AUR 4 are basically just git repositories including the `PKGBUILD` but also `.SRCINFO` files, which are actually generated from the PKGBUILD and normally not part of the previous (private) repositories.

Why isn't the script just splitting the repository and calling `mksrcinfo`? What is all that stuff copied from pkgbuild-introspection?

**Comment by ido** [comment]
Feel free to submit a pull request.

**Comment by JonnyJD** [comment]
Yes I did open a PR now since just using `mksrcinfo` seems to work.
When I wrote this issue I was actually puzzled about what needs to be done.
