### ISSUE TITLE
docker-git no longer compiles on i686

### ISSUE THREAD

**Issue by goodwillcoding** [ido/packages-archlinux#61]
The following error occurs, basically dockerinit is no longer created by dynbinary

    # WARNING! I don't seem to be running in the Docker container.
    # The result of this command might be an incorrect build, and will not be
    #   officially supported.
    #
    # Try this instead: make all
    #
    --> Making bundle: dynbinary (in bundles/1.9.0-dev/dynbinary)
    Created binary: bundles/1.9.0-dev/dynbinary/dockerinit-1.9.0-dev
    sha1sum: bundles/1.9.0-dev/dynbinary/dockerinit-1.9.0-dev: No such file or directory
    md5sum: dockerinit-1.9.0-dev: No such file or directory
    ==> ERROR: A failure occurred in build().
        Aborting...
    ==> ERROR: Makepkg was unable to build docker-git.

**Comment by flaccid** [comment]
This is probably dependent on https://github.com/ido/packages-archlinux/pull/62

**Comment by flaccid** [comment]
Verified #62 does the job and will avoid fatal error of `open docs/man/*.md: no such file or directory`.
