### ISSUE TITLE
docker-git doesn't compile on i686 (Error at build())

### ISSUE THREAD

**Issue by vmonteco** [ido/packages-archlinux#69]
I try to install docker on my Archlinux machine but I encounter two problems :

1) The first one is an invalid md5 sum for docker.service. (Fixed by pull request #66)

2) If I pass this first problem, I get the following at the building :

    ==> Extracting sources...
      -> Creating working copy of docker git repo...
    Reset branch 'makepkg'
    ==> Starting pkgver()...
    ==> Updated version: docker-git 1:1.9.0.dev.18712.0137e3e-1
    ==> Starting prepare()...
    ==> Removing existing $pkgdir/ directory...
    ==> Starting build()...
    # WARNING! I don't seem to be running in the Docker container.
    # The result of this command might be an incorrect build, and will not be
    #   officially supported.
    #
    # Try this instead: make all
    #
    
    bundles/1.9.0-dev already exists. Removing.
    
    ---> Making bundle: dynbinary (in bundles/1.9.0-dev/dynbinary)
    Created binary: bundles/1.9.0-dev/dynbinary/dockerinit-1.9.0-dev
    Building: bundles/1.9.0-dev/dynbinary/docker-1.9.0-dev
    # _/home/vmonteco/Downloads/docker-git/src/docker/docker
    /usr/lib/go/pkg/tool/linux_386/link: running gcc failed: exit status 1
    /tmp/go-link-282662828/000007.o: In function `__udivdi3':
    (.text+0x8ebc0): multiple definition of `__udivdi3'
    /tmp/go-link-282662828/000003.o:(.text+0x740): first defined here
    collect2: error: ld returned 1 exit status
    
    ==> ERROR: A failure occurred in build().
        Aborting...

What could cause this issue?

**Comment by x3rus** [comment]
Hi ,
I have the same issue with the AUR docker-experimental-git :-/. 

here some information about the packages installed with version, 
$ pacman -Q | egrep 'linux |gcc|^go'
gcc 5.2.0-2
gcc-libs 5.2.0-2
go 2:1.5.1-2
go-md2man 1.0.2-1
gobject-introspection 1.44.0-1
gobject-introspection-runtime 1.44.0-1
libutil-linux 2.26.2-1
linux 4.1.6-1
util-linux 2.26.2-1

any help is welcome !

**Comment by vmonteco** [comment]
@x3rus Do you have a i686 computer too?

**Comment by x3rus** [comment]
@vmonteco  Yes , of course , I tried workaround , tried to install docker version 1.8.3  , but I have others errors ... :-/  with opencontainer and seccomp .

**Comment by vmonteco** [comment]
Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d
    OS/Arch (client): linux/arm
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d
    OS/Arch (server): linux/arm

Here is what is installed on my raspberry pi, I guess it has to be the same docker version that worked previously on my i686 computer. Perhaps it could be possible to use old sources? I can't try it right now but I'll try later!

**Comment by NickCis** [comment]
Reverting go to [1.4.2](http://ala.seblu.net/packages/g/go/go-2%3A1.4.2-2-i686.pkg.tar.xz) and checking out this 786b29d revition in git, makes the package build.

```
$ diff PKGBUILD PKGBUILD.old 
60d59
<   git checkout 786b29d
```

The version of go ***must be downgraded***. It doesn't build lastest go from the arch repository. Aparently docker doesn't support go 1.5.x yet. If you read the [docker file](https://github.com/docker/docker/blob/master/Dockerfile#L86) used for docker compilation, it uses go 1.4.3.

**Comment by vmonteco** [comment]
I manually installed Go 1.4.2 (The one I used on my raspberry). I succeeded to build docker-git by removing 'go' from dependencies and adding `git checkout 786b29d` after the `cd docker`.

I had to modify docker.service as @NickCis suggested to be able to start `docker.service`.

I succeeded to build an **archlinux** image.

But I have the same error as described in https://github.com/docker/docker/issues/16256

**Comment by vmonteco** [comment]
It finally worked (adding "--exec-opt native.cgroupdriver=cgroupfs" to the docker.service entrypoint seems to work, as suggested in https://github.com/docker/docker#16256), I tried to fork it and to modify it.

At this point I don't really know how to make the AUR package install the correct Go version (1.4.2) so I assumed it was already installed.

Perhaps automatically building an archlinux image at installation could also be a good idea?

**Comment by NickCis** [comment]
I really don't think that it would be a good idea to make the docker-git package downgrade go (also, i don't know if is it possible).

In my opinion, a better idea would be that docker-git package depends on a docker-go package which installs go 1.4.2 in an specific (non standard) directory (in order not to conflict with the regular go package), or that docker-git package would provide this specific version of go.

As regards images, remember that you'll have to build them, as most of the images in docker hub are for 64bits systems.

I've uploaded two images for 32bits docker:

* [nickcis/fedora-32](https://hub.docker.com/r/nickcis/fedora-32/)
* [nickcis/debian-32](https://hub.docker.com/r/nickcis/debian-32/)

The scripts i've used in order to build them are in my [github](https://github.com/NickCis/docker-build-scripts).

**Comment by vmonteco** [comment]
This makes sense. But I don't know at the moment how to make this specific go installation. I'll try tomorrow if I have the time.
I don't use go for something else so it doesn't bother me yet.

Anyway hank you for your advices that permitted me to solve this problem. (I really wasn't able to work with docker for more than a month).

**Comment by NickCis** [comment]
As regards the go packaging, i'm not a go expert, but i think that setting some enviromental variables will be enought, you should check [go installation guide](https://golang.org/doc/install/source#environment).

As a base for create the PKGBUILD, you could use the [go's PKGBUILD](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/go). I think that changing `GOROOT_FINAL`, `GOROOT_BOOTSTRAP` to custom location (for example: `/usr/lib/go-docker`), and then changing the paths where the `install` and `cp` commands copy  the binaries will be enough.

I **suppose** that when docker will be built, you should set go's enviromental variables correctly, specially `GOPATH` (*not* using `AUTO_GOPATH`). **I really do not know if this will succeed.**

**Comment by NickCis** [comment]
I've managed to build some packages specifically for running go on `i686` systems. Versions are hardcoded, you can find them on my [github](https://github.com/NickCis/packages-archlinux).

I've not send any pr as these modifications aren't suitable for the `docker-git` package.

Basically a there are two packages, a `go-docker` package with `go` version hardcoded at `1.4.2` is installed in `/usr/lib/go-docker`, and a `docker-i686` package with `docker` version hardcoded at `1.7.1`  which depends on `go-docker`.

I'll will try to submit these packages to `aur`.
