### ISSUE TITLE
tn42xx: 0.3.6.12.2

### ISSUE THREAD

**Issue by adlerweb** [ido/packages-archlinux#77]
Upstream released 0.3.6.12.2, old URL is now 404. Already updated in AUR: https://aur.archlinux.org/cgit/aur.git/commit/?h=tn40xx&id=57a9a711d2bfca3144338a94e9a8c3b3016b2eda

**Comment by ido** [comment]
Thanks.  I've disowned that package since I do not have the card available to me.  If you'd like to adopt it, feel free.
