### ISSUE TITLE
POCO 1.7.2 ODBC / Raspberry Pi Make Error

### ISSUE THREAD

**Issue by iquestor** [ido/packages-archlinux#79]
I have a Raspberry Pi 3 where POCO has installed previously without using ODBC. Now I want to add ODBC.

I installed unixODBC: 
sudo apt-get install unixodbc unixodbc-dev
sudo apt-get install libmyodbc 

When executing "sudo make -s" In POCO Folder on Rapsberry Pi 3 I get the following error:

DBC.make:65: *** No ODBC library found. Please install unixODBC or iODBC or specify POCO_ODBC_LIB and try again.  Stop.
Makefile:253: recipe for target 'Data/ODBC-libexec' failed
make: *** [Data/ODBC-libexec] Error 2

I see this has been an issue in 1.6, but seems to still be an issue. Anyone have this problem?

**Comment by ido** [comment]
Updated.  Thanks @rosswhitfield

**Comment by iquestor** [comment]
Was there no answer to this issue?

**Comment by ido** [comment]
Raspberry Pi is ARM. I don't have a RPi nor is ARM officially supported.

**Comment by ido** [comment]
Also, I think you have the wrong github project for this issue...  These are ArchLinux packages, not Debian/Ubuntu packages.

**Comment by iquestor** [comment]
ISO

Thanks for your email. I have the right archive for my OS. I just posted issue in wrong area. I am using POCO on raspberry Pi for a while just have issue compiling ODBC.

Sent from my iPhone

On Jul 17, 2016, at 7:16 PM, Ido Rosen <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, I think you have the wrong github project for this issue... These are ArchLinux packages, not Debian/Ubuntu packages.

-

**Comment by ido** [comment]
Okay, no problem.  (I was also confused by the "apt-get install" -- you meant pacman -S?  Or are you on Debian/Raspbian?)

You probably will find the archlinuxarm.org forum more helpful in this area. AFAIK, that's where Arch ARM packages are born.

**Comment by iquestor** [comment]
Raspbian. I'll check that forum. Thanks.

Sent from my iPhone

On Jul 17, 2016, at 9:13 PM, Ido Rosen <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay, no problem. (I was also confused by the "apt-get install" -- you meant pacman -S? Or are you on Debian/Raspbian?)

You probably will find the archlinuxarm.org<http://archlinuxarm.org> forum more helpful in this area. AFAIK, that's where Arch ARM packages are born.

-

**Comment by ido** [comment]
Raspbian is Debian-based, ArchLinuxARM.org won't help you.  You need to talk to the Raspbian people.  ArchLinux is a different distribution entirely.
